version: 2
jobs:
 build:
   docker:
     - image: circleci/php:7.3-stretch-node-browsers
     - image: postgres:9.6
       environment:
        TEST_DATABASE_URL: postgresql://root@localhost/circle_test
   working_directory: ~/repo
   steps:
     - checkout
     - run:
          name: Install Laravel Test pre-requisites
          command: |
            sudo apt update
            sudo apt install libpq-dev zlib1g-dev libsqlite3-dev -y
            sudo -E docker-php-ext-configure pgsql -with-pgsql=/usr/local/pgsql
            sudo -E docker-php-ext-install pgsql pdo_pgsql
            sudo -E docker-php-ext-install bcmath
     - restore_cache:
          keys:
            # "composer.lock" can be used if it is committed to the repo
            - v1-dependencies-{{ checksum "composer.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
     - run:
          name: Install Composer Packages
          command: composer install
     - save_cache:
          key: composer-v1-{{ checksum "composer.lock" }}
          paths:
            - vendor
     - run:
          name: Setup Code Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
     - run: touch storage/testing.sqlite
     - run: php artisan migrate --env=testing --database=sqlite_testing --force
     - run:
          name: Run tests
          command: |
            ./cc-test-reporter before-build
            composer test
            ./cc-test-reporter after-build --coverage-input-type clover --exit-code $?
